### ISSUE TITLE
A Jenkins job should be configurable to be triggered by a specific DeployDB event

### ISSUE THREAD

**Issue by rtyler** [lookout/deploydb-jenkins-plugin#1]
@orrc this issue might need to be broken tnto more concrete parts, since I don't know what I'm doing.

The [different kinds of webhook events](https://github.com/lookout/deploydb/tree/master/features/api/webhook) should be selectable trigger criteria to start a job.

**Comment by orrc** [comment]
Should it be possible to add multiple trigger event types to a job, e.g. trigger Job X if "deployment created" *or* "deployment started" is received?

**Comment by rtyler** [comment]
@orrc yeah, I think that's reasonable to support

**Comment by orrc** [comment]
I split out the basic stuff into #6, the event-specific and multiple event stuff will go here.

Being able to differentiate between event types will depend on https://github.com/lookout/deploydb/issues/106.
