### ISSUE TITLE
Report success/failure back to DeployDB after a triggered job completes

### ISSUE THREAD

**Issue by rtyler** [lookout/deploydb-jenkins-plugin#3]
[See this API](https://github.com/lookout/deploydb/blob/master/features/api/promotion/creating.feature#L7-L18)

it's pretty boolean:

 * Jenkins job success: `"status" : "SUCCESS"`
 * Anything else: `"status": "FAILURE"`

**Comment by orrc** [comment]
How does Jenkins know which DeployDB hostname/path to POST to?
If the deployment URL was part of the inbound webhook to Jenkins, that would be helpful. Otherwise we'd likely require global config in Jenkins pointing to DeployDB instance(s), and a way of mapping job configs to DeployDB instances.

I assume the `1` in `/api/deployments/1/promotions` corresponds to the [top-level `id` value](https://github.com/lookout/deploydb/blob/522d165/features/api/webhook/deploymentCreated.feature#L19) in the inbound webhook?

Do the `jenkins-smoke` and `infoUrl` values in the outbound payload refer directly to the triggered Jenkins job name and build URL, respectively?
What happens in the case where one inbound hook triggers builds of multiple Jenkins jobs?

**Comment by rtyler** [comment]
> If the deployment URL was part of the inbound webhook to Jenkins, that would be helpful. Otherwise we'd likely require global config in Jenkins pointing to DeployDB instance(s), and a way of mapping job configs to DeployDB instances.

Will you file a separate issue to make it globally configurable now. I'll add an issue into lookout/deploydb to make sure we send an appropriate header in the webhook request with the location of DeployDB in the future.

> I assume the 1 in /api/deployments/1/promotions corresponds to the top-level id value in the inbound webhook?

Yes, that is the Deployment ID for the deployment that was created in that webhook

> Do the jenkins-smoke and infoUrl values in the outbound payload refer directly to the triggered Jenkins job name and build URL, respectively?

That feature file is a little confusing, 'jenkins-smoke' is supposed to be the job name. So if I triggered "my-stupid-test-job" I would expect the plugin to POST back with a name field of `my-stupid-test-job`

The `infoUrl` should just be the URL of the build.

> What happens in the case where one inbound hook triggers builds of multiple Jenkins jobs?

Let's make them report all as separate promotion calls

**Comment by orrc** [comment]
> I'll add an issue into lookout/deploydb to make sure we send an appropriate header in the webhook request with the location of DeployDB in the future.

@rtyler Please do :)

> [See this API](https://github.com/lookout/deploydb/blob/master/features/api/promotion/creating.feature#L7-L18)

So all the feature file examples I could find for the reporting webhook URL and its payload seem to be related to deployment creation. i.e. There are no samples of what should happen if a Jenkins build is triggered by any other event types.

What is the expected mapping between event type and reporting URL path?

>> If the deployment URL was part of the inbound webhook to Jenkins, that would be helpful.

This could be an alternative. If the event webhook included the `reportUrl` (or so) which Jenkins should POST to for that event, then DeployDB would have a bit more flexibility, e.g. the URL layout could change (if desired) without having to change the Jenkins plugin.

**Comment by rtyler** [comment]
> So all the feature file examples I could find for the reporting webhook URL and its payload seem to be related to deployment creation. i.e. There are no samples of what should happen if a Jenkins build is triggered by any other event types.
>
> What is the expected mapping between event type and reporting URL path?

Provided we have a Deployment ID in the webhook payload, then the linked API (promotion creation) is correct. If our usecases evolve to where we're going to want feedback from a triggered mechanism (like the Jenkins plugin) then I think we'll have to re-evaluate the relationship between webhooks (event) and reporting APIs.

> This could be an alternative. If the event webhook included the reportUrl (or so) which Jenkins should POST to for that event, then DeployDB would have a bit more flexibility, e.g. the URL layout could change (if desired) without having to change the Jenkins plugin.

IMO this is too prescriptive of what the webhooks are to be used for. They will eventually be used for tools like Hubot to send data into group chats and things like that, which don't have a "report loop" to close
