### ISSUE TITLE
Triggered jobs should expose DeployDB metadata as environment variables

### ISSUE THREAD

**Issue by rtyler** [lookout/deploydb-jenkins-plugin#4]
Environment variables seem to be the right way to go about this.

For a webhook payload [like this](https://github.com/lookout/deploydb/blob/master/features/api/webhook/deploymentCompleted.feature#L20-L34) I wonder if just under-score segmenting the values would make sense, z.B. `DDB_ENVIRONMENT="pre-prod"` and `DDB_ARTIFACT_ID=1`

I'd be open to changing this, since it will have an impact on how a test running inside the job might know what to test

**Comment by orrc** [comment]
That's fine.

Should we automatically convert *all* keys in the payload to uppercased, underscore-separated values and export them, or hardcode a few select keys?

**Comment by tommysullivan** [comment]
before i comment i wanna double check my assumptions:

1. deploydb deployment completion event occurs
2. configured webhook is POSTed to with JSON of deployment
3. deploydb-jenkins-plugin hosts a web server that receives the POST
4. ????
5. the user acceptance test gradle task of our artifact gets called

So, what happens in 4 and who does that work? 

a) Clearly before (5) can happen, someone will have needed to use the artifact id to figure out the appropriate test artifact and pull it down.

b) As of this writing, our ruby cli for bluffdale expects a stage name passed as an argument. This could be changed to use environment variables. However, I want to call attention to how this environment name is *used* by our ruby cli - it is used to vary the configuration values used to (i) obtain keymaster tokens and (ii) connect to (or mock) consul - based on a yaml configuration included with our cli's source. Perhaps the responsibility of (i) belongs in our tests; but as illustrated in the red block at the top of our architecture diagram couple weeks back (internal so can't link), I am not so sure about (ii). It may belong "above" our artifact, where parallelization of jobs occurs.

**Comment by rtyler** [comment]
@orrc I was suggesting that we convert *all* keys and use the `DDB` prefix.

DeployDB doesn't use underscores for key names (e.g. `created_at`) but instead relies on snake case (e.g. `createdAt`) so we could use underscores to delimit the nested keys. For example `payload['artifact']['id']` would map to `DDB_ARTIFACT_ID`

**Comment by orrc** [comment]
Jolly good; that's what I had in mind.

**Comment by blaines** [comment]
+2
