### ISSUE TITLE
What should happen if sending the report webhook from Jenkins fails?

### ISSUE THREAD

**Issue by orrc** [lookout/deploydb-jenkins-plugin#9]
As per #3, Jenkins will attempt to make an HTTP request to DeployDB to report success/failure.

DeployDB may be unreachable, the tubes may be clogged, the network cable may be unplugged etc.

What to do in this case? Log an error? Persist to disk and retry X times?

**Comment by rtyler** [comment]
I suggest logging a error to disk and failing the build if possible.

I think the plugin should make a reasonable attempt, i.e. a couple retries, to contact DeployDB though
